%矩形序列响应
xn_1=[ones(1,8),zeros(1,62)];
B=[0.05,0.05];A=[1,-0.9];%差分方程的系数向量
yn_1=filter(B,A,xn_1);%矩形序列的响应
n=0:length(xn_1)-1;
figure(1)
subplot(1,3,1);
stem(n,yn_1,'.');
xlabel("n");
ylabel("y(n)");
title("系统对x(n)=R_{8}(n)的响应");
%单位阶跃序列响应
xn_2=ones(1,70);
yn_2=filter(B,A,xn_2);%单位阶跃序列的响应
subplot(1,3,2);
stem(n,yn_2,".");
xlabel("n");
ylabel("y(n)");
title("系统对x(n)=u(n)的响应");
%单位脉冲响应
xn_3=[1,zeros(1,69)];
yn_3=filter(B,A,xn_3);%单位脉冲响应
subplot(1,3,3);
stem(n,yn_3,".");
xlabel("n");
ylabel("y(n)");
title("系统对x(n)=\delta(n)的响应");
