clc;clear
xn=[ones(1,8),zeros(1,2)];%矩形输入序列
%h1(n)的输出响应
h_1=ones(1,10);%单位脉冲响应
y_1=conv(h_1,xn);%输出序列
n_1=0:(length(xn)+length(h_1)-2);
n_2=0:length(h_1)-1;
subplot(2,2,1);%第一个分图，h1（n）单位脉冲响应
stem(n_2,h_1,".");
xlabel("n");
ylabel("h_{1}(n)");
title("系统单位脉冲响应h_1(n)");
subplot(2,2,2);%第二个分图，系统的输出
stem(n_1,y_1,".");
xlabel("n");
ylabel("y(n)");
title("x_{1}(n)=R_{8}(n)和h_{1}(n)的卷积");
%h2(n)的输出响应
h_2=[1,2.5,2.5,1,zeros(1,6)];%单位脉冲响应
y_2=conv(h_2,xn);%输出序列
subplot(2,2,3);%第三个分图，h2（n）单位脉冲响应
stem(n_2,h_2,".");
xlabel("n");
ylabel("h_{2}(n)");
title("系统单位脉冲响应h_2(n)");
subplot(2,2,4);%第四个分图，系统的输出
stem(n_1,y_2,".");
xlabel("n");
ylabel("y(n)");
title("x_{1}(n)=R_{8}(n)和h_{2}(n)的卷积");